


export default [
    {img:"/images/Jihyo.jpg" ,name: "Jihyo", age: 26, ranking: 1, description: "Park Jihyo is a South Korean singer, songwriter, and dancer. She is best known as the leader and main vocalist of the popular K-pop girl group TWICE. Jihyo was born on February 1, 1997, in Guri, Gyeonggi Province, South Korea. She was discovered and signed by JYP Entertainment after winning second place in the 8th JYP Open Audition in 2005. Since then, she has been an active member of TWICE, which debuted in 2015 and has achieved immense success both in South Korea and internationally. Jihyo is known for her powerful vocals, leadership skills, and charismatic stage presence.", birthday: "September 16th, 2004"},
    {img:"/images/Tzuyu.jpg",name: "Tzuyu", age: 23, ranking: 4, description: "Chou Tzuyu is a Taiwanese singer, dancer, and visual of the popular K-pop girl group TWICE. She was born on June 14, 1999, in Tainan, Taiwan. Tzuyu was scouted by JYP Entertainment at the age of 13 and became a trainee under the agency before debuting with TWICE in 2015. Tzuyu is known for her stunning visuals, dancing abilities, and sweet singing voice. She has gained popularity both in South Korea and internationally and is considered one of the most prominent Taiwanese K-pop idols. Tzuyu has also been praised for her charity work, including donating to disaster relief efforts in her home country of Taiwan."},
    {img:"/images/MIna.jpg",name: "Mina", age: 26, ranking: 8, description: "Myoui Mina, also known as Mina, is a Japanese singer, dancer, and member of the popular K-pop girl group TWICE. She was born on March 24, 1997, in San Antonio, Texas, United States, but grew up in Nishinomiya, Hyōgo Prefecture, Japan. Mina joined JYP Entertainment after successfully auditioning for the company's 13th open audition in Japan in 2013. She made her debut as a member of TWICE in 2015 and has since gained a large fan following for her elegant and graceful dancing, soothing vocals, and charming personality. Mina has also been known for her unique fashion sense and her ability to speak several languages, including Japanese, Korean, and English. In 2019, she took a hiatus from TWICE's activities due to health concerns but returned to the group in 2020."},
    {img:"/images/Dahyun.jpg",name: "Dahyun", age: 24, ranking: 3, description: "Kim Dahyun is a South Korean singer and dancer who is a member of the popular K-pop girl group TWICE. She was born on May 28, 1998, in Seongnam, Gyeonggi Province, South Korea. Dahyun was recruited by JYP Entertainment after performing at a church and became a trainee under the agency before debuting with TWICE in 2015. She is known for her lively and energetic personality, as well as her talent in singing, dancing, and rapping. Dahyun has also gained popularity for her unique visuals and charming smile. In addition to her activities with TWICE, Dahyun has appeared on several variety shows and music programs as a host and guest."},
    {img:"/images/Momo.jpg",name: "Momo", age: 26, ranking: 5, description:"Hirai Momo, commonly known as Momo, is a Japanese singer, dancer, and member of the popular K-pop girl group TWICE. She was born on November 9, 1996, in Kyotanabe, Kyoto, Japan. Momo trained at the EXPG dance school in Osaka, Japan, before participating in the reality show Sixteen, which was produced by JYP Entertainment and served as a survival program for the formation of TWICE. Momo was selected as a member of the group and made her debut in 2015. She is known for her powerful and precise dance skills, as well as her bright and cheerful personality. Momo has also been recognized for her contributions to TWICE's music and choreography. In addition to her activities with TWICE, Momo has appeared on several television shows and music programs, showcasing her dancing abilities." },
    {img:"/images/Nayeon.jpg",name: "Nayeon", age: 27, ranking: 4, description: "Nayeon, whose full name is Im Na-yeon, is a South Korean singer and dancer who is a member of the popular K-pop girl group TWICE. She was born on September 22, 1995, in Seoul, South Korea. Nayeon was scouted by JYP Entertainment after participating in the company's 7th open audition and became a trainee under the agency. She made her debut as a member of TWICE in 2015 and has since gained a large fan following for her powerful vocals, charming personality, and stunning visuals. Nayeon is also known for her natural leadership abilities and has often taken on the role of TWICE's spokesperson in interviews and public appearances. In addition to her activities with TWICE, Nayeon has also appeared on several television shows and music programs, showcasing her talents as a performer and host." },
    {img:"/images/Sana.jpg",name: "Sana", age: 26, ranking: 6, description: "Sana, whose full name is Minatozaki Sana, is a Japanese singer and dancer who is a member of the popular K-pop girl group TWICE. She was born on December 29, 1996, in Tennōji-ku, Osaka, Japan. Sana became a trainee under JYP Entertainment after participating in a Japanese audition held by the agency in 2012. She made her debut as a member of TWICE in 2015 and has since gained a large fan following for her cute and bubbly personality, as well as her stunning visuals and vocals. Sana is also known for her unique dance style, which incorporates traditional Japanese dance elements. In addition to her activities with TWICE, Sana has appeared on several variety shows and music programs, showcasing her talents as a performer and entertainer."},
    {img:"/images/Jeongyeon.jpg",name: "Jeongyeon", age: 26, ranking: 9, description: "Jeongyeon, whose full name is Yoo Jeong-yeon, is a South Korean singer and dancer who is a member of the popular K-pop girl group TWICE. She was born on November 1, 1996, in Suwon, Gyeonggi Province, South Korea. Jeongyeon was discovered by JYP Entertainment during a public audition in 2010 and became a trainee under the agency. She made her debut as a member of TWICE in 2015 and has since gained a large fan following for her powerful vocals, unique style, and charismatic personality. Jeongyeon is also known for her short hair, which has become one of her trademark features. In addition to her activities with TWICE, Jeongyeon has also appeared on several television shows and music programs, showcasing her talents as a performer and host. However, she has been on hiatus from the group's activities since 2020 due to health reasons."},
    {img:"/images/Chaeyoung.jpg",name: "Chaeyoung", age: 24, ranking: 2, description: "Chaeyoung, whose full name is Son Chae-young, is a South Korean singer, rapper, and dancer who is a member of the popular K-pop girl group TWICE. She was born on April 23, 1999, in Seoul, South Korea. Chaeyoung was scouted by JYP Entertainment after performing at a local dance competition and became a trainee under the agency. She made her debut as a member of TWICE in 2015 and has since gained a large fan following for her rapping skills, unique fashion sense, and artistic talents. Chaeyoung has also been involved in writing and producing several of TWICE's songs, including Precious Love and Get Loud. In addition to her activities with TWICE, Chaeyoung has also collaborated with other artists and participated in several television shows and music programs, showcasing her talents as a performer and artist."}
    

]

